import 'package:room_scanner_core/room_scanner_core.dart';
import 'package:test/test.dart';

void main() {
  test('English converts all drawing lengths to inches without changing the project', () {
    final room = _room('r', -0.3048, 0.6096, 3.048, 1.524).copyWith(
      features: [
        WallFeature(
          id: 'door',
          type: FeatureType.door,
          start: ARPoint(x: 0, y: 0, z: 0.6096),
          end: ARPoint(x: 0.9144, y: 0, z: 0.6096),
        ),
      ],
    );
    final before = room.toJson();
    final metric = _entities(
      DxfExportBuilder.build([room], languageCode: 'es'),
    );
    for (final locale in ['en', 'en-US', 'en_GB']) {
      final dxf = DxfExportBuilder.build([room], languageCode: locale);
      expect(dxf, contains(r'$INSUNITS' '\r\n70\r\n1\r\n'));
      expect(dxf, contains(r'$MEASUREMENT' '\r\n70\r\n0\r\n'));
      expect(dxf, contains(r'$LUNITS' '\r\n70\r\n4\r\n'));
      final imperial = _entities(dxf);
      expect(imperial.length, metric.length);
      for (var i = 0; i < metric.length; i++) {
        for (final code in [10, 20, 30, 11, 21, 31, 40]) {
          if (!metric[i].containsKey(code)) continue;
          expect(
            double.parse(imperial[i][code]!),
            closeTo(double.parse(metric[i][code]!) / 0.0254, 1e-8),
          );
        }
        for (final code in [0, 8, 50, 51]) {
          expect(imperial[i][code], metric[i][code]);
        }
      }
      final labels = imperial
          .where((e) => e[8] == 'MEASUREMENTS')
          .map((e) => e[1]);
      expect(labels, contains('10 ft 0 in'));
      expect(labels, contains('5 ft 0 in'));
      expect(room.toJson(), before);
    }
  });

  test(
    'imperial labels reduce fractions and carry rounded inches into feet',
    () {
      for (final entry in {
        0.0381: '0 ft 1 1/2 in',
        0.304799: '1 ft 0 in',
      }.entries) {
        final room = _room('r', 0, 0, entry.key, 1);
        final labels = _entities(
          DxfExportBuilder.build([room], languageCode: 'en'),
        ).where((e) => e[8] == 'MEASUREMENTS').map((e) => e[1]);
        expect(labels, contains(entry.value));
      }
    },
  );

  test('Spanish regional locales preserve metric geometry and labels', () {
    final room = _room('r', 0, 0, 3.048, 2);
    expect(
      DxfExportBuilder.build([room], languageCode: 'es-AR'),
      DxfExportBuilder.build([room]),
    );
  });

  test(
    'exports model-space metres, layers and X/Z as X/Y without mutation',
    () {
      final room = _room('r', -2, 3, 4, 5);
      final before = room.toJson();
      final dxf = DxfExportBuilder.build([room]);
      expect(dxf, contains('\$ACADVER\r\n1\r\nAC1015'));
      expect(dxf, contains('999\r\nGenerated by ARchScan\r\n'));
      expect(dxf, contains('\$INSUNITS\r\n70\r\n6'));
      expect(dxf.endsWith('0\r\nEOF\r\n'), isTrue);
      for (final layer in [
        'WALLS',
        'DOORS',
        'WINDOWS',
        'ROOM_NAMES',
        'MEASUREMENTS',
      ]) {
        expect(dxf, contains('2\r\n$layer\r\n'));
      }
      expect(
        dxf,
        contains('2\r\nWALLS\r\n70\r\n0\r\n62\r\n7\r\n'
            '6\r\nCONTINUOUS\r\n370\r\n35\r\n'),
      );
      expect(
        dxf,
        contains('2\r\nMEASUREMENTS\r\n70\r\n0\r\n62\r\n7\r\n'
            '6\r\nCONTINUOUS\r\n370\r\n13\r\n'),
      );
      final walls = _entities(dxf)
          .where((e) => e[0] == 'LINE' && e[8] == 'WALLS')
          .toList();
      expect(walls, hasLength(4));
      expect(walls.first[10], '-2.0');
      expect(walls.first[20], '3.0');
      expect(walls.first[30], '0.0');
      expect(walls.first[11], '2.0');
      expect(walls.first[21], '3.0');
      expect(room.toJson(), before);
    },
  );

  test('removes duplicate full and partial shared wall segments', () {
    for (final shift in [0.0, 1.0]) {
      final entities = _entities(
        DxfExportBuilder.build([
          _room('a', 0, 0, 2, 2),
          _room('b', 2, shift, 2, 2),
        ]),
      );
      final walls = entities.where((e) => e[0] == 'LINE' && e[8] == 'WALLS');
      final length = walls.fold<double>(
        0,
        (sum, e) =>
            sum +
            (double.parse(e[11]!) - double.parse(e[10]!)).abs() +
            (double.parse(e[21]!) - double.parse(e[20]!)).abs(),
      );
      expect(length, closeTo(shift == 0 ? 14 : 15, 1e-8));
    }
  });

  test('orthogonalizes only the technical DXF and draws dimension lines', () {
    final room = RoomModel(
      id: 'technical',
      name: 'technical',
      type: RoomType.other,
      isClosed: true,
      points: [
        ARPoint(x: 0, y: 0, z: 0),
        ARPoint(x: 4, y: 0, z: 0),
        ARPoint(x: 4.052, y: 0, z: 3),
        ARPoint(x: 0.018, y: 0, z: 3.04),
      ],
    );
    final before = room.toJson();
    final entities = _entities(DxfExportBuilder.build([room]));
    final walls = entities
        .where((entity) => entity[0] == 'LINE' && entity[8] == 'WALLS')
        .toList();
    final dimensions = entities
        .where((entity) => entity[0] == 'LINE' && entity[8] == 'MEASUREMENTS')
        .toList();

    expect(walls, hasLength(4));
    expect(dimensions, hasLength(12));
    expect(double.parse(walls[1][10]!), closeTo(4, 0.000001));
    expect(double.parse(walls[1][11]!), closeTo(4, 0.000001));
    expect(double.parse(walls[2][21]!), closeTo(3.00045, 0.00001));
    expect(double.parse(walls[3][10]!), closeTo(0, 0.000001));
    expect(room.toJson(), before);
  });

  test('cuts a wall gap and draws a shared door once', () {
    final door = WallFeature(
      id: 'door',
      type: FeatureType.door,
      start: ARPoint(x: 0.5, y: 0, z: 0),
      end: ARPoint(x: 1.5, y: 0, z: 0),
    );
    final room = _room('r', 0, 0, 2, 2).copyWith(features: [door]);
    final entities = _entities(
      DxfExportBuilder.build([room, room.copyWith(id: 'copy')]),
    );
    expect(entities.where((e) => e[0] == 'ARC'), hasLength(1));
    final bottom = entities
        .where(
          (e) =>
              e[0] == 'LINE' &&
              e[8] == 'WALLS' &&
              double.parse(e[20]!) == 0 &&
              double.parse(e[21]!) == 0,
        )
        .toList();
    expect(bottom, hasLength(2));
    expect(bottom[0][11], '0.5');
    expect(bottom[1][10], '1.5');
  });

  test('preserves both hinge choices and both swing directions in the plan frame', () {
    for (final hinge in DoorHingeSide.values) {
      for (final swing in DoorSwingSide.values) {
        final door = WallFeature(
          id: 'd',
          type: FeatureType.door,
          start: ARPoint(x: 0, y: 0, z: 0),
          end: ARPoint(x: 1, y: 0, z: 0),
          doorHingeSide: hinge,
          doorSwingSide: swing,
        );
        final entities = _entities(
          DxfExportBuilder.build([
            _room('r', 0, 0, 2, 2).copyWith(features: [door]),
          ]),
        );
        final arc = entities.singleWhere((e) => e[0] == 'ARC');
        final leaf = entities.singleWhere(
          (e) => e[0] == 'LINE' && e[8] == 'DOORS',
        );
        expect(double.parse(arc[10]!), hinge == DoorHingeSide.start ? 0 : 1);
        expect(double.parse(arc[40]!), 1);
        expect((double.parse(arc[51]!) - double.parse(arc[50]!)) % 360, 90);
        final modelDirection =
            (swing == DoorSwingSide.left ? 1 : -1) *
            (hinge == DoorHingeSide.start ? 1 : -1);
        // The technical export uses the mirrored 2D plan frame, so the
        // persisted model swing is intentionally inverted at export time.
        expect(double.parse(leaf[21]!), -modelDirection);
      }
    }
  });

  test(
    'windows are separate editable lines and names cannot inject DXF records',
    () {
      final room = _room('r', 0, 0, 2, 2).copyWith(
        name: 'Baño\n0\nEOF \\U+0041',
        features: [
          WallFeature(
            id: 'w',
            type: FeatureType.window,
            start: ARPoint(x: 0.5, y: 0, z: 0),
            end: ARPoint(x: 1.5, y: 0, z: 0),
          ),
        ],
      );
      final dxf = DxfExportBuilder.build([room]);
      expect(dxf.codeUnits.every((c) => c < 128), isTrue);
      final entities = _entities(dxf);
      expect(entities.where((e) => e[8] == 'WINDOWS'), hasLength(3));
      final name = entities.singleWhere((e) => e[8] == 'ROOM_NAMES')[1]!;
      expect(name, contains('Ba\\U+00F1o 0 EOF'));
      expect(name, contains('\\U+005CU+0041'));
    },
  );

  test(
    'open paths have no invented closing wall; invalid points are rejected',
    () {
      final room = _room('r', 0, 0, 2, 2).copyWith(isClosed: false);
      expect(
        _entities(DxfExportBuilder.build([room]))
            .where((e) => e[0] == 'LINE' && e[8] == 'WALLS'),
        hasLength(3),
      );
      expect(
        () => DxfExportBuilder.build([
          room.copyWith(points: [ARPoint(x: double.nan, y: 0, z: 0)]),
        ]),
        throwsArgumentError,
      );
    },
  );
}

RoomModel _room(String id, double x, double z, double width, double depth) =>
    RoomModel(
      id: id,
      name: id,
      type: RoomType.other,
      isClosed: true,
      points: [
        ARPoint(x: x, y: 0, z: z),
        ARPoint(x: x + width, y: 0, z: z),
        ARPoint(x: x + width, y: 0, z: z + depth),
        ARPoint(x: x, y: 0, z: z + depth),
      ],
    );

List<Map<int, String>> _entities(String dxf) {
  final lines = dxf.split('\r\n');
  final result = <Map<int, String>>[];
  var inside = false;
  Map<int, String>? current;
  for (var i = 0; i + 1 < lines.length; i += 2) {
    final code = int.parse(lines[i]);
    final value = lines[i + 1];
    if (code == 2 && value == 'ENTITIES') {
      inside = true;
      continue;
    }
    if (!inside) continue;
    if (code == 0) {
      if (current != null) result.add(current);
      if (value == 'ENDSEC') break;
      current = <int, String>{};
    }
    current?[code] = value;
  }
  return result;
}
